import Head from "next/head";
import Navbar from "../Components/Sections/Navbar";
import styles from "../styles/Home.module.css";
import Footer from "../Components/Sections/Footer";
import Mainnews from "../Components/news/Mainnews";
import axios from "axios";

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>New next app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>

      <main className={styles.main}>
        <Mainnews mainNews={props.mainNews} />
      </main>

      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  );
}
export async function getStaticProps() {
  const mainNews = await axios
    .get(
      "https://newsdata.io/api/1/news?apikey=pub_641191b3f3f50a8e27cfc4dde13de18a91cc&q=cryptocurrency"
    )
    .then((res) => {
      return res.data.results;
    })
    .catch((err) => {
      console.log("error occured while fetching main news", err);
      return [];
    });
  return {
    props: {
      mainNews,
    },
    revalidate: 10000,
  };
}
