import Head from "next/head";
import styles from "../styles/Home.module.css";
import Mainnews from "../Components/news/Mainnews";
import axios from "axios";

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>New next app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Mainnews mainNews={props.mainNews} />
      </main>
    </div>
  );
}
export async function getStaticProps() {
  const mainNews = await axios
    .get("http://localhost:3000/api/news")
    .then((res) => {
      return res.data.articles;
    })
    .catch((err) => {
      console.log("error occured while fetching main news", err);
      return [];
    });
  return {
    props: {
      mainNews,
    },
    revalidate: 10000,
  };
}
